spring:
  security:
    saml2:
      identityprovider:
        entity-id: "http://localhost:8080/saml2/idp/metadata"
        signing:
          credentials:
            - private-key-location: "classpath:credentials/rp-private.key"
              certificate-location: "classpath:credentials/rp-certificate.crt"
        relyingparty:
          registration:
            sample-sp:
              entity-id: "http://localhost:9000/saml2/service-provider-metadata/sample-sp"
              assertion-consumer-service-location: "http://localhost:9000/login/saml2/sso/sample-sp"
              single-logout-service-location: "http://localhost:9000/logout/saml2/slo/sample-sp"
              single-logout-service-response-location: "http://localhost:9000/logout/saml2/slo/sample-sp"
